Controllers/ClassStreamController.cs
using System;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class ClassStreamController : Controller
    {
        private Models.ApplicationDbContext _context = new Models.ApplicationDbContext();
        // GET: ClassStream
        public ActionResult Index()
        {
            var classStreams = _context.ClassStreams.Include("Class").ToList();
            return View(classStreams);
        }

        public ActionResult Details(int? id)
        {
            // Fetch the ClassStream along with the related Class data
            var classStream = _context.ClassStreams
                .Include("Class") // Use the string-based Include method
                .SingleOrDefault(cs => cs.ClassStreamId == id);

            if (classStream == null)
            {
                return HttpNotFound();
            }

            return View(classStream);
        }

    }
}

Views/ClassStream/Details.cshtml
@model WebApplication1.Models.ClassStream

@{
    ViewBag.Title = "Class Stream Details";
}

<h2>Class Stream Details</h2>

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Details for @Model.StreamName</h3>
    </div>
    <div class="panel-body">
        <div class="form-horizontal">
            <div class="form-group">
                @Html.LabelFor(model => model.StreamName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.StreamName)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Class.Name, "Class", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DisplayFor(model => model.Class.Name)
                </div>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        @Html.ActionLink("Back to List", "Index", new { area = "" }, new { @class = "btn btn-default" })
    </div>
</div>

Views/ClassStream/Index.cshtml
@model IEnumerable<WebApplication1.Models.ClassStream>

@{
    ViewBag.Title = "Class Streams List";
}

<h2>Class Streams List</h2>

<p>
    @Html.ActionLink("Create New Class Stream", "Create", "ClassStream", new { area = "" }, new { @class = "btn btn-primary" })
</p>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.First().StreamName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.First().Class.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var classStream in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => classStream.StreamName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => classStream.Class.Name)
                </td>
                <td>
                    @Html.ActionLink("View Details", "Details", new { id = classStream.ClassStreamId }, new { @class = "btn btn-info btn-sm" })
                </td>
            </tr>
        }
    </tbody>
</table>